### PR TITLE
NO-ISSUE modified code so that it catches instances of the component …

### PR DESCRIPTION
**Pull request by shawnveltman**
This includes an update that catches the blade-ui-kit formatting.

```php
<x-heroicon-o-cloud-download class="h-7 w-7" />
```

becomes 

```php
<x-heroicon-o-cloud-arrow-down class="h-7 w-7" />
```

### CODE REVIEW

**Comment by shawnveltman** [comment]
Thanks for your amazing work on this!!!  It made my upgrade SO much easier.  Since I was using the blade-ui-kit, I had to make a tiny change, but once that was done it saved my bacon (144 files changed on my project).  

Much, much appreciated!

**Comment by HelgeSverre** [comment]
> Thanks for your amazing work on this!!! It made my upgrade SO much easier.

You're welcome!


>  I had to make a tiny change, but once that was done it saved my bacon

Could you mind explaining this change, I'm not entirely sure what it does, other than split the regex replacement into a separate method.

I did notice one bug i have not fixed yet, unrelated to this, but might be somewhat related, and that is that it does not account for newlines directly after the icon name so 

`<x-heroicon-o-name\n` will not be caught properly, need to fix the regex for that later.

**Comment by shawnveltman** [comment]
The main change (I think) is in these 2 lines:
// New pattern for Blade component syntax
                $bladePattern = "#<x-heroicon-{$variant}-".preg_quote($oldName, '#')."([\\s>])#";
                $contents = $this->replacePattern($contents, $bladePattern, "<x-heroicon-{$variant}-{$newName}$1", $replaced);

Essentially - the original version wasn't catching the format <x-heroicon-anything class="h-4 w-4" .../> in my code for some reason.  Once I added that, it worked like a charm.  
Example from my code that the first one didn't catch but the 2nd one would:

```php
                                        <x-heroicon-o-plus class="mr-2 h-7 w-7" />
```

That's from my current code, so it won't match against your list, but hopefully it provides some insight.

**Comment by HelgeSverre** [comment]
Issue mentioned in the PR should be fixed in [v1.1.0.](https://github.com/HelgeSverre/blade-heroicons-upgrader/releases/tag/v1.1.0).

**Pull request closed without merging**
